######################################################################
# Automatically generated by qmake (2.01a) Sun May 12 19:32:37 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += calculate.h Calculator.h operations.h types.h
SOURCES += calculate.cpp Calculator.cpp main.cpp operations.cpp
