######################################################################
# Automatically generated by qmake (2.01a) Mon May 13 09:33:29 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += calculate.h Calculator.h types.h
SOURCES += calculate.cpp Calculator.cpp main.cpp
