######################################################################
# Automatically generated by qmake (2.01a) Tue May 14 11:53:56 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . include
INCLUDEPATH += .

# Input
HEADERS += include/calculate.h
SOURCES += calculate.cpp main.cpp
